version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - chainlit_postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - chainlit_postgres_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    volumes:
      - chainlit_pgadmin_data:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - chainlit_postgres_network
    depends_on:
      - postgres

networks:
  chainlit_postgres_network:
    driver: bridge

volumes:
  chainlit_postgres_data:
  chainlit_pgadmin_data: